language: python
sudo: false
python:
  - "2.7"
  - "3.6"
env:
  - IPYTHON=3
  - IPYTHON=4
  - IPYTHON=5
  - IPYTHON=6

addons:
  postgresql: "9.3"

install:
  - pip install tox

script:
  - if [[ $TRAVIS_PYTHON_VERSION = '2.7' ]]; then tox -e py27-ipython$IPYTHON,flake8; fi
  - if [[ $TRAVIS_PYTHON_VERSION = '3.6' ]]; then tox -e py36-ipython$IPYTHON,flake8; fi

branches:
  only:
    - master
